"""
Your goal in this project is to break RSA when the public modulus 
N is generated incorrectly.
But suppose a developer decides to generate the first prime p
by choosing a random number R
and scanning for a prime close by.  The second prime q
is generated by scanning for some other random prime also close to R.

"""
import math
from xmlrpc.client import Boolean
#Exercise 1
#The following N is a product of two primes p and q where |p-q|<2N^(1/4)
#If A=(p+q)/2 it can be shown that A-sqrt(N)<1 and A is in between p and q
#So there exist x s.t. p+x=A and q-x=A and we know that A=ceil(sqrt(N)) by the inequation showed previously
N1=179769313486231590772930519078902473361797697894230657273430081157732675805505620686985379449212982959585501387537164015710139858647833778606925583497541085196591615128057575940752635007475935288710823649949940771895617054361149474865046711015101563940680527540071584560878577663743040086340742855278549092581
A=int(math.isqrt(N1))
A=A+1 if A*A<N1 else A
x=int(math.isqrt(A**2-N1))
#We need to find the smallest of the two integers in this case p and we find it as following
p1=A-x
q1=A+x
print(p1)


#Exercise 2
#Now we have a different challenge |p-q|<2^11*N^(1/4) so the inequality change for the following A-sqrt(N)<2^20
#So we need to try scanning for A upwards from sqrt N so that we can find the factorization of N
def factorization(A:int,N:int)->Boolean:
    """
    This function verifies if a given A could give us the factorization of N following the equation A=(p+q)/2 and x=sqrt(A**2-N)
    Args:
        A(int): A is the number we are trying for as a middle point of p and q (we know it exist because both numbers are odds)
        N(int): N is the module
    Returns:
        is_factor(Boolean): we return True in case the value of A gives us a correct factorization and False otherwise
    """
    x=int(math.isqrt(A**2-N))
    #We try to get a proper value for p if it is a factor of N we return true otherwise we return False
    p=A-x
    if N%p==0:
        return True
    return False
#Now, we use the function created to look for the proper value of A
N=648455842808071669662824265346772278726343720706976263060439070378797308618081116462714015276061417569195587321840254520655424906719892428844841839353281972988531310511738648965962582821502504990264452100885281673303711142296421027840289307657458645233683357077834689715838646088239640236866252211790085787877
sqrt_N=math.isqrt(N)
for A in range(sqrt_N,sqrt_N+2**20):
    A=A+1 if A*A<N else A
    if factorization(A,N):
        x=int(math.isqrt(A**2-N))
        p=A-x
        print(p)
        break

#Exercise 3
#For the following exercise we need to find the factorization of the module N which satisfies |3p-2q|<N^(1/4) 
#So we define our new A as A=(3p+2q)/2 and for numbers that are big enough we can assume
#That A is in between 3p and 2q and furthermore A is really close to sqrt(6N)
#It can be shown that A^2-6N<sqrt(N)/4 so we can finally show that A-sqrt(6N)<1 and we can use the same idea as in the previous exercises to find the factorization of N
N=720062263747350425279564435525583738338084451473999841826653057981916355690188337790423408664187663938485175264994017897083524079135686877441155132015188279331812309091996246361896836573643119174094961348524639707885238799396839230364676670221627018353299443241192173812729276147530748597302192751375739387929
# We work with 2A = 3p + 2q, so (2A)^2 = 9p^2 + 12pq + 4q^2
# (2A)^2 - 24N = (3p - 2q)^2  so that we can ensure that the value of A we are trying is correct by checking if the value of (2A)^2 - 24N is a perfect square
A = math.isqrt(24 * N) + 1

x_sample = A**2 - 24*N
assert x_sample >= 0

x = math.isqrt(x_sample)
assert x*x == x_sample  

# 2A + x = 2*(3p+2q)/2 + (3p-2q) = 3p+2q + 3p-2q = 6p
# so p = (a_ + x) / 6  OR  p = (a_ - x) / 6
p = (A - x) // 6
q = N // p

print("p:", p)

#Exercise 4
#In this challenge we are given a e= 65537 for the RSA algorithm and The ASCII plaintext was encoded using PKCS v1.5 before the RSA function was applied.
#but the separator used here is '0x00', not '0xFF' as in the lecture, and the N is the one of the first eercise so we already now the factorization
Phi_n=(p1-1)*(q1-1)
#Now we need to find the value of d which is the inverse of e mod Phi_n
def extended_eucledian_inverse(A, N):
    t, new_t = 0, 1
    r, new_r = N, A

    while new_r != 0:
        quotient = r // new_r
        t, new_t = new_t, t - quotient * new_t
        r, new_r = new_r, r - quotient * new_r

    if r > 1:
        return None 

    if t < 0:
        t += N

    return t
d=extended_eucledian_inverse(65537, Phi_n)

ciphertext=22096451867410381776306561134883418017410069787892831071731839143676135600120538004282329650473509424343946219751512256465839967942889460764542040581564748988013734864120452325229320176487916666402997509188729971690526083222067771600019329260870009579993724077458967773697817571267229951148662959627934791540
#Now we can get the plaintext by doing the following operation
plaintext=pow(ciphertext,d,N1)
hex_plaintext = hex(plaintext)
print(hex_plaintext)
#based on this we get 0x2 so we need to remove the 00 separator only the first time so we use the function find
separator_index = hex_plaintext.find('00', 2)
#We replace from the index we find
actual_hex_msg = hex_plaintext[separator_index + 2:]
decoded_message = bytes.fromhex(actual_hex_msg).decode('ascii')
print(decoded_message)